- spec/money_spec.rb
Without them, I was getting an annoying warning in Vim:
'ambiguous first argument; put parentheses or a space even after `-' operator'
> wrapping negative numbers in parentheses

- lib/money/money.rb
- lib/money/money/constructors.rb
- spec/money/constructors_spec.rb
- spec/money_spec.rb
First commit: aliases constructor methods like "Money.usd_dollar" to their 3-letter ISO codes (e.g. Money.usd).
Second commit: extracted these functions to a module as they're closely related and modular (and the parent 'money.rb' file is huge.)
Third commit: added similar methods for British pounds (if we're going to include CAD then it only makes sense to include GBP too).
> Extracting 'constructor' functions to a module, adding aliases and GBP

- lib/money/money/formatting.rb
docs for ':html_wrap_symbol' and ':symbol_position' options.
> adding more documentation for Money#format [ci skip]

- config/currency_iso.json
Hi, this is an update for currency iso value for BYR according to standart:
http://www.currency-iso.org/en/home/tables/table-a1.html
> Improve BYR format. Delete subunit

- CHANGELOG.md
- lib/money/currency.rb
- spec/currency_spec.rb
- `Currency#<=>` sorts alphabetically by `id` if the `priority`s are the same, and no longer raises an error if one of the priorities is missing. (This also fixes one type of error described at #479)
- `Currency` implements `Enumerable`.
> Currency extends Enumerable, and is more robust when sorting

- spec/bank/base_spec.rb
- spec/bank/single_currency_spec.rb
- spec/bank/variable_exchange_spec.rb
- spec/currency_spec.rb
This way we don't have to qualify every reference to 'Currency' etc by prefacing it with 'Money'
> wrapping spec files in the 'Money' class/modules

- lib/money/bank/variable_exchange.rb
A very minor improvement. `Numeric#to_money` is no longer part of this gem, so i think it's preferable to use `Money.new` in the docs instead.
Cheers! :beers:
> Use Money.new instead of Numeric#to_money in VariableExchange docs

- CHANGELOG.md
- README.md
- lib/money/money.rb
- spec/money_spec.rb
Hi!
I'd like to propose the addition of a `Money.from_amount` constructor method, which creates a Money from a given amount in the currency's *units*. 
I think building money values from amounts in units is a pretty common use case, and i was a bit confused when i couldn't find a method to do so in the latest versions of this gem. I now know that methods like `Numeric#to_money` were moved to Monetize, and i agree with that decision, but i think that a method like `Money.from_amount` *does* have its place in Money. Mainly because Money already knows about amounts and fractional amounts, with `Money#amount` and `Money#fractional` respectively. And also because some applications don't need the complex parsing from strings that Monetize provides, and i'd rather avoid adding methods to …
> Add Money.from_amount

- money.gemspec
- spec/currency_spec.rb
- spec/money/arithmetic_spec.rb
- spec/money/formatting_spec.rb
- spec/money_spec.rb
- spec/spec_helper.rb
Just a couple of minor tweaks to the specs.
Remove an unnecessary `Array.wrap` definition from spec_helper.rb and use the `Kernel#Array` method instead.
Remove repetition of setting and un-setting `Money.infinite_precision` on specs and use an RSpec "shared context" tagged as `:infinite_precision` instead.
> Minor spec tweaks

- CHANGELOG.md
- config/currency_iso.json
The [ISO standard](http://www.currency-iso.org/en/home/tables/table-a1.html) indicates that there are 4 decimal places to the "Minor unit" for the CLF currency.
> Change CLF exponent from 0 to 4

- AUTHORS
- CHANGELOG.md
- lib/money/money/arithmetic.rb
- spec/money/arithmetic_spec.rb
A special circumstance for `#==` to recognize that:
The **value of 0 in currency A** is always equal to **the value of 0 in currency B**
This was initially inspired by an issue on [money-rails (#325)](https://github.com/RubyMoney/money-rails/issues/325)
> 0 in one currency should equal 0 in any other currency

- CHANGELOG.md
- config/currency_iso.json
Minor unit was the jeon but no longer used. See http://en.wikipedia.org/wiki/South_Korean_won.
> only one unit in South Korean Won

- CHANGELOG.md
- README.md
- lib/money/bank/variable_exchange.rb
- lib/money/rates_store/memory.rb
- spec/bank/variable_exchange_spec.rb
- spec/rates_store/memory_spec.rb
Decouple exchange rate storage from `Money::Bank::VariableExchange` by introducing new `Money::RatesStore::Memory` class.
`VariableExchange` uses new class by default but can be instantiated with custom stores as well.
This change should be backwards compatible.
It should be able to reuse the `VariableExchange` bank with custom storage mechanisms. Ie. in one of my apps I use `ActiveRecord`, but it could also be Redis, the filesystem or others. It shouldn't be necessary to subclass, monkey-patch or otherwise extend `VariableExchange` in order to swap the storage mechanism.
Using composition instead of inheritance allows us to design custom strategies for storing and retrieving exchange rates. Some examples:
```ruby
bank = Money::Bank::VariableExchange.new
bank = …
```
> Decouple exchange rates storage from VariableExchange bank

- lib/money/rates_store/memory.rb
I might have introduced a potential threading bug with #516
This change makes sure that ANY change to the state of `RatesStore::Memory` is protected by the mutex.
Banks and stores are essentially globals, so this should prevent race conditions when setting the temporary `@in_transaction` flag.
> Any state change should be protected by mutex.

- CHANGELOG.md
- config/currency_iso.json
- spec/money_spec.rb
I ran into a problem converting the CLP to USD using the Google Currency gem, you can read more here: https://github.com/RubyMoney/google_currency/issues/38
The Chilean Peso is improperly converting to other currencies because 1 CLP is not the smallest version of that currency.  There are supposed to be 100 centavos that make up 1 CLP. 
Google's finance site currently shows the conversion rate as 29555 CLP = 47.2880 USD
Inside Ruby, however, I see this:
2.1.3 :067 > Money.new(2955500, "CLP").exchange_to(:USD).to_f
=> 4728.8
2.1.3 :068 > Money.new(29555, "CLP").exchange_to(:USD).to_f
=> 47.28
> CLP subunit_to_unit change from 1 to 100

- config/currency_iso.json
According to http://en.wikipedia.org/wiki/ISO_4217 JOD exponent is 3.
Central Bank of Jordan is also states that 1/2 qirsh coin (i.e.
5 fulūs) is still in circulation (http://www.cbj.gov.jo/pages.php?local_type=26&category=14&subcategory=28)
> Fix Jordanian Dinar subunit (100 -> 1000).

- README.md
I entirely missed the formatting options upon reading the readme.  Added a short section in usage, and turned what was a note in i18n into a section header to highlight the usefulness of the formatting module.
> Add intro to formatting in usage and name the section

- lib/money/money.rb
- lib/money/money/arithmetic.rb
- spec/money/arithmetic_spec.rb
https://github.com/RubyMoney/money/pull/470 made a breaking change to the behavior of `Money#==`. This reverts the change in https://github.com/RubyMoney/money/pull/470 while still removing the deprecation warning.
Ruby 2.2 warns that `<=>` should return `nil` on invalid comparisons rather than raise an error.
Fixes https://github.com/RubyMoney/money/issues/469.
> Fix Money#== and Ruby 2.2 deprecation warning

- lib/money/bank/base.rb
- lib/money/currency.rb
- money.gemspec
Hi all,
It seems to me that using the whole `thread_safe` gem for a simple use case is quite an overkill. Here's a quick change that gets rid of the dependency, leveraging a built-in ruby mutex instead.
Also, notice the removal of `self.class.instances[id] = self` on line 263. Because `instances` Hash is initialized with a block, this line is not needed.
> Remove `thread_safe` dependency

- lib/money/currency.rb
- spec/currency_spec.rb
Another quick one:
I've noticed that `|| super` in the overriden `new` method is never called, because `instances` hash is initialized with a block that calls `initialize`. So in order to make it more readable and remove duplication the initialization and caching are achieved by `instances[id] ||= super`.
> Refactor Currency#new method

- README.md
On a Retina screen, the PNG badges (or shields if you will) don't look so great. I updated the them to the SVG variants.
Before:
After:
> Use SVG badges in readme

- lib/money/bank/variable_exchange.rb
- lib/money/money.rb
- lib/money/money/arithmetic.rb
- lib/money/money/constructors.rb
- spec/bank/variable_exchange_spec.rb
- spec/money/arithmetic_spec.rb
- spec/money/constructors_spec.rb
- spec/money_spec.rb
I can see from the spec previously included that it was desired that subclassing would work, but the implementation was incomplete.
Scenario:
class SpecialMoney < Money
end
SpecialMoney.new(val1) + SpecialMoney.new(val2)
All specs remain green, and it works as expected. New specs have been added to attempt to prevent regression.
> Allow subclassing money

- AUTHORS
- CHANGELOG.md
- lib/money/money/arithmetic.rb
- spec/money/arithmetic_spec.rb
When used with [Monetize](https://github.com/RubyMoney/monetize) gem Money can act confusingly when compared with non Money objects due to the conversion with `#to_money`.
```ruby
require 'monetize'
Money.new(100, 'USD') == Money.new(100, 'GBP').to_s
#==> true?
Money.new(100, 'GBP') == 1.0
#==> true?
```
I propose removing this implicit conversion in favour of being explicit with a `Money` in the comparison to avoid confusion and unexpected behaviour. If the object being compared is not a `Money` or a subclass then the comparison should fail.
> Do not attempt to convert value being compared

- CHANGELOG.md
- lib/money/money/arithmetic.rb
- spec/money/arithmetic_spec.rb
In the future Ruby releases `#==` will no longer rescue exceptions and expects `#<=>` to return `nil` if the comparison is inappropriate (because in Money `#==` is provided by [Comparable](http://ruby-doc.org/core-2.2.3/Comparable.html))
I know this has come up in a couple of times before but Ruby is complaining louder in spec output now (because some specs should be breaking and raising `Money::Bank::UnknownRate`).
I guess this follows on from work done in #528
> Return nil when currency cannot be converted for comparison

- CHANGELOG.md
- spec/currency_spec.rb
- spec/money/arithmetic_spec.rb
- spec/rates_store/memory_spec.rb
While working on the gem I noticed a few Ruby warnings that could be easily fixed and also a couple of specs executing comparisons but not making any assertions.
These were found by running:
```
$ bundle exec rspec --warnings
```
**Side note:** Today I learned Ruby does not like `private` `attr_reader`, the alternative is to raise visibility to `protected` or just use the instance variables. https://bugs.ruby-lang.org/issues/10967
> Fix specs not making any assertions

- .travis.yml
Figure Travis may as well be testing against the latest:
- 2.1.6 => 2.1.7
- 2.2.2 => 2.2.3
> Update Travis to use latest MRI Ruby stable

- CHANGELOG.md
- lib/money/money/formatting.rb
- spec/money/formatting_spec.rb
Formatting within this rule used `Currency#decimal_mark`. The problem is this represents the formatting for this currency and ignores any i18n delimiter and separator set by the application.
Fixes issue reported in #545
> Fix issue with rounded_infinite_precision not using localised decimal mark

- README.md
Add gem https://github.com/phlegx/money-currencylayer-bank to README.md.
See issue #552
> Add gem money-currencylayer-bank to implementations list.

- lib/money/currency/heuristics.rb
If I try to find a currency like ```Nicaraguan Córdoba``` I can do it with method ```Money::Currency#analyze``` like this:
```ruby
Money::Currency.analyze('Nicaraguan Córdoba')
```
But if I use ```Nicaraguan Cordoba``` instead of ```Nicaraguan Córdoba``` I get no results.
```ruby
Money::Currency.analyze('Nicaraguan Cordoba')
```
So, the search tree should first transliterate leaves with ```I18n.transliterate(leaf)``` or something similar.
See line [money/currency/heuristics.rb#L53](https://github.com/RubyMoney/money/blob/master/lib/money/currency/heuristics.rb#L53)
**This code solves the problem**
```ruby
class Money
class Currency
module Heuristics
private
def currencies_by_name
{}.tap do |r|
table.each do |dummy,c|
name_parts = I18n.transliterate(c[:name]).downcase.split # Here we make …
```
> Add transliteration to currency name search.

- README.md
`Currency` is not top-level constant and cannot be used without
namespace.
This line
Money.new(1000, "USD") == Money.new(1000, Currency.new("USD"))
will fail with exception
NameError: uninitialized constant Currency
> Add `Money::` namespace to `Currency` class in README usage examples

- config/currency_iso.json
The official value of "symbol_first" is false for currency HRK
> Set "symbol_first: false" for currency HRK

- lib/money/money/arithmetic.rb
- spec/money/arithmetic_spec.rb
Resurrected @semmons99's commit from last year, that properly handles coercion for non-Money objects. Raises a TypeError in cases like 0 - Money.new(1), where it otherwise produces a wrong result.
Here's some discussion around this — RubyMoney/money-rails#343
P.S. reopened a PR because of the failing TravisCI build. There's an issue with a "thread safe" test that's failing randomly.
> Ensure coerce only applies to multiplication

- AUTHORS
- CHANGELOG.md
- lib/money/money/arithmetic.rb
- spec/money/arithmetic_spec.rb
This PR should fix the inconsistent behavior when Money.new(100) <=> 1 was giving you nil while 1 <=> Money.new(100) was raising a TypeError. Based on the discussion in #535 I think it was agreed that comparison should raise a TypeError in both cases.
This should fix #563 too.
> Raise TypeError when comparing with non-Money objects

- lib/money/money/formatting.rb
I found an other way to fix this issue by working inside a `base.class_eval` block rather than calling private methods on the base, which I think is more standard/clean way to do this.
Fixes an issue on Ruby 2.3, when calling those dynamically defined methods we get a
NoMethodError (private method `separator' called for #<Money fractional:0 currency:USD>).
> Ensure formatting methods are defined as public with class_eval

- spec/spec_helper.rb
Much easier to debug stuff with a focus flag available in rspecs. 
For examples see https://www.relishapp.com/rspec/rspec-core/v/3-4/docs/filtering/inclusion-filters
> Allow focus filter in specs

- lib/money/money/arithmetic.rb
- spec/money/arithmetic_spec.rb
Comparable#== no more rescue exceptions of #<=> in ruby >= 2.3
@see https://bugs.ruby-lang.org/issues/7688 and #576 
This change is backward compatible and fix the last known issue with 2.3.0-preview2.
> Update <=> to return nil if the comparison is inappropriate

- config/currency_iso.json
there is a new smallest denomination in Belarus since July 1, 2015, when 50 BYR coupon was annulled
> fix smallest_denomination for BYR

- AUTHORS
Some entries were simply in the wrong place, eg Douglas Miller as the
last entry of the file.
Also, all the authors beginning in 'Y' were previously between 'S' and 'T'.
> Sort the AUTHORS file

- README.md
Corrected output to match the output of running the commands in `irb`.
major_currencies:
* corrected misspelling of :gbp.
* Added missing :aud and :jpy
all_currencies:
* output corrected to include ':' character before 'all' currency code
> Fix simulated output of major_currencies and all_currencies in README.md

- .travis.yml
- lib/money/currency.rb
- spec/currency_spec.rb
Add jruby latest stable with openjdk on travis
I just had to round a spec on currency
> Travis jruby

- lib/money/money/arithmetic.rb
- spec/money/arithmetic_spec.rb
Avoid duplication of arithmethic methods for Money and coerced Numeric,
treat them as fully commutative operations.
See #606
> Fix coercion issues

- CHANGELOG.md
- config/currency_iso.json
- spec/money/formatting_spec.rb
We've had some customers write in and inform us that the currency symbol for Danish Krone is `kr.` and not `kr`. Wikipedia [agrees](https://en.wikipedia.org/wiki/Danish_krone). That's all! :heart:
> fix symbol for Danish Krone (DKK)

- CHANGELOG.md
- lib/money/money/formatting.rb
> fix Money::Formatting#format docs

- lib/money/money.rb
I noticed a few typos and inconsistencies in the documentation for `money`. Hope this helps! :smile_cat:
> Typo Fixes and Consistency Changes

- lib/money/money/formatting.rb
- spec/money/formatting_spec.rb
When
- an explicit `thousands_separator` option is given that matches the [computed `decimal_mark`](https://github.com/RubyMoney/money/blob/741d11e7dbc6a4edcd6e17168f87d717fca64889/lib/money/money/formatting.rb#L294) (whether returned by locale with i18n or by Money's yaml config)
- an explicit `decimal_mark` option is given that does not match the [computed `decimal_mark`](https://github.com/RubyMoney/money/blob/741d11e7dbc6a4edcd6e17168f87d717fca64889/lib/money/money/formatting.rb#L294) (again, by i18n or yaml)
- a number is formatted that does not have a decimal component
Then
- the rightmost `thousands_separator` is clobbered by the [`apply_decimal_mark_from_rules ` formatting](https://github.com/RubyMoney/money/blob/741d11e7dbc6a4edcd6e17168f87d717fca64889/lib/money/money/formatting.r …
> fix formatting for edge case with i18n/yaml settings

- README.md
money-json-rates has been deprecated since June 30th 2015, and their own
readme refers to currencylayer as the new version
> Replaces deprecated gem with new version

- config/currency_iso.json
Currently the smallest HUF denomination is the 5 Ft coin:
https://en.wikipedia.org/wiki/Hungarian_forint
> fixed HUF smallest denomination

- LICENSE
Closes #639 
I have very little idea about software licenses, so i don't know if this is worth it, but proposing this change was simpler than adding a longer discussion comment it :stuck_out_tongue:
> Mention "MIT" in license text

- README.md
https://github.com/subvisual/money-uphold-bank
I build this bank integration to work with the API from https://uphold.com/
It's mainly because I'm building a couple of products for this API, but it has the interesting aspect of supporting Litecoin, Bitcoin, Ethereum and any other currency that might eventually get added to Uphold itself
(these crypto currencies are only visible by the Money gem if you register them manually)
> Adding reference to money-uphold-bank

- Gemfile
JSON gem has dropped support for older rubies (https://github.com/flori/json/blob/master/CHANGES.md).
This will lock json at `1.8.3` for older rubies.
> Lock json at 1.8.3 for ruby 1.9

- CHANGELOG.md
- lib/money/money/formatting.rb
- spec/money/formatting_spec.rb
I am not sure if this was a design decision, but currently calling `format` with both `disambiguate` and `symbol` options set to `true` will just return the ambiguous symbol:
```
Money.new(1999_98, "USD").format(disambiguate: true, symbol: true)
=> "$1,999.98"
```
It felt more natural to me if the behavior was to instead use the disambiguate symbol in this case:
```
Money.new(1999_98, "USD").format(disambiguate: true, symbol: true)
=> "US$1,999.98"
```
> Do not ignore disambiguate option when symbol: true in `format` method

- README.md
In recents version of ActiveRecord `find_by_*` was replaced with `find_by(conditions_hash)` and `find_or_initialize_by_*` was replaced with `find_or_initialize_by(conditions_hash)`
This updates the example on the README to reflect the changes.
> Update example for recent versions of ActiveRecord

- config/currency_iso.json
Changed thousands separator to another which is more used in Czech Republic.
> Change czk thousand separator to most used

- money.gemspec
This PR removes the `post_install_message` outlining API changes in Money version 6; it's been more than three years, and produces noisy output on every `bundle install`.
Thanks :)
> money.gemspec: remove post_install_message

- lib/money/money/constructors.rb
- lib/money/money/formatting.rb
- spec/money/constructors_spec.rb
- spec/money/formatting_spec.rb
I18n calls are quite expensive, so caching this gives us an increase in performance of about 20%. Here's an example:
```ruby
res = Benchmark.measure do
100_000.times do
Money.euro(250).format
end
end
puts res
```
Without caching:
```
=> 17.560000   0.060000  17.620000 ( 17.639144)
```
with caching:
```
=> 14.410000   0.040000  14.450000 ( 14.445001)
```
Although I had to remove the freeze on the empty Money object. The whole empty object pre-caching seems like a very premature optimization
> Cache I18n calls for better performance

- lib/money/currency.rb
- lib/money/money.rb
- lib/money/money/arithmetic.rb
- spec/money/arithmetic_spec.rb
- spec/money_spec.rb
Hi,
This solves some deprecation warning for ruby 2.4.
See https://bugs.ruby-lang.org/issues/12005
> Fixnum is deprecated in ruby 2.4.

- lib/money/money/constructors.rb
- lib/money/money/formatting.rb
- spec/money/constructors_spec.rb
Fixes a bug introduced by #666 not allowing to call `#format` on a frozen Money object.
> Rollback #666 + different caching solution

- config/currency_iso.json
Solves https://github.com/RubyMoney/money/issues/677
> eliminate subunits for forints

- lib/money/money.rb
- spec/money_spec.rb
This scenario happened to me: 
```
currency_code = nil (returned by data store)
amount = 500
Money.from_amount(amount, currency_code).cents results in 
#<NoMethodError: undefined method `subunit_to_unit' for nil:NilClass>
```
Basically currency_code did not default to the default_currency value and was accepted as nil.
> fix self_amount constructor accepting nil currency_code

- config/currency_iso.json
- config/currency_non_iso.json
This also adds a `disambiguate_symbol` for XFU, fixing a failing test
#682
> Fix symbol for UZS

- config/currency_iso.json
At its introduction in 1991, the currency was officially called nuevo sol ("new sol"), but on November 13, 2015, the Peruvian Congress voted to rename the currency simply sol
https://en.wikipedia.org/wiki/Peruvian_sol
> Peruvian Sol

- money.gemspec
Patch version bumps should not cause any breaking changes. I18n 0.8.1 has been released and contains a minor fix. Relaxing the version constraint to allow any version before 0.9 would enable updating the gem without a change in Money.
> Relax i18n version constraint to allow patch version updates

- config/currency_iso.json
- spec/money/formatting_spec.rb
- Related to https://github.com/RubyMoney/money/issues/678
- Set VND currency to display dong symbol at the end
> [Issue #678] VND currency should have symbol_first: false

- config/currency_non_iso.json
GBX is in wide use in the world of stock exchanges. https://en.wikipedia.org/wiki/Penny_sterling
> Add support for the British Penny (GBX)

- config/currency_iso.json
The currency pattern for the BBD is defined as "¤#,##0.00" in the ICU library.
http://demo.icu-project.org/icu-bin/locexp?d_=en&_=en_BB
> Display the BBD $ symbol before digits.

- lib/money/rates_store/memory.rb
- spec/rates_store/memory_spec.rb
Discovered a bug when I was testing conversion with a rails app. The test helper was setting a memory store with mock rates. When I ran just the single test there was no issues, but running the whole suite made the currency conversion fail.
I finally figured out it was due to the marshal dump, the arguments were in reverse order. This fixes the issue, and adding spec for the marshal dump.
> Make marshal dump work for memory store

- lib/money/money/arithmetic.rb
- spec/money/arithmetic_spec.rb
Current behaviour:
```ruby
Money.new(0, 'USD').eql? Money.new(0, 'AUD') # => true
Money.new(0, 'USD') == 0                     # => true
Money.new(0, 'USD') == Money.new(0, 'AUD')   # => false (due to no rate being set)
Money.disallow_currency_conversion!
Money.new(0, 'USD').eql? Money.new(0, 'AUD') # => true
Money.new(0, 'USD') == 0                     # => true
Money.new(0, 'USD') == Money.new(0, 'AUD')   # => Money::Bank::DifferentCurrencyError: No exchanging of currencies allowed: 0.00 AUD to USD
```
The behaviour of `Money.new(0, 'USD') == Money.new(0, 'AUD')` seems inconsistent to the other examples. Let's change it to:
```ruby
Money.new(0, 'USD') == Money.new(0, 'AUD')   # => true (no rate set)
Money.disallow_currency_conversion!
Money.new(0, 'USD') == Money.new(0, 'AUD')   # => …
```
> Allow comparing cross currency when both are zero

- CHANGELOG.md
- lib/money/money/arithmetic.rb
- spec/money/arithmetic_spec.rb
Re the discussion in PR https://github.com/RubyMoney/money/pull/705#issuecomment-306064365 it was decided that the `#eql?` method should align with our `#hash` implementation.
[docs](https://ruby-doc.org/core-2.4.1/Object.html#method-i-hash):
>This function must have the property that `a.eql?(b)` implies `a.hash == b.hash`. 
In the current implementation this property is not upheld in the case where both `a` and `b` have zero value:
```ruby
a = Money.new(0, 'USD')
b = Money.new(0, 'AUD')
a.eql?(b) #=> true
a.hash == b.hash #=> false
```
Remove the special handling of zero value money instances from the `#eql?` implementation. Instead we have a hard rule: both `fractional` and `currency` must be equal for `#eql?` to return `true`.
In the above example:
```ruby
a = Money.new(0, 'USD')
b = …
```
> eql? returns false for 0 value moneys of differing currency

- config/currency_iso.json
Micro update here. I noticed that the `iso_code` for XTS was all lowercase in the data, but according to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) it should be all uppercase just like any other code.
> Fix for XTS ISO code

- README.md
The example in the readme file is outdated. I made the adjustment with the new name of the thousands_separator and decimal_mark attributes.
> Adjusted attribute name in readme text

- config/currency_iso.json
It was using postal mark: http://unicodelookup.com/#〒/1
> Fix KZT symbol

- config/currency_non_iso.json
Add offshore Chinese Yuan (CNH). Most properties same like in CNY.
(reference: https://en.wikipedia.org/wiki/Renminbi)
> Add Chinese Yuan Offshore (CNH)

- .travis.yml
Seems like bundler shipped with rubies on TravisCI is very old (1.7.6). Which I think is causing this issue:
This PR should fix it.
> Update the bundler on Travis to the latest available version

- lib/money/money.rb
- spec/money_spec.rb
> Don't round when verifying allocation splits

- AUTHORS
- lib/money/money/constructors.rb
- spec/money/constructors_spec.rb
Steps to reproduce the bug:
1. start a new ruby console by running `irb`
2. Run the following code
```rb
require 'money'
Money.zero(:usd)
Money.zero
```
3. then you will see an error like
```
NoMethodError: undefined method `priority' for :usd:Symbol
```
Here is another way to reproduce the issue
```rb
h = {usd: Money.new(1)}
h[Money.default_currency]
```
When we are trying to look up a value by Money::Currency, it invokes `currency <=> :usd`, since `:usd` doesn't have `priority` method, that's why we see the error.
Not sure if I should change CHANGELOG because this is a bugfix
> Fix a bug for `Money.zero`

- lib/money/bank/variable_exchange.rb
- lib/money/money.rb
- spec/money/arithmetic_spec.rb
- spec/money/formatting_spec.rb
- spec/money_spec.rb
This removes one deprecation warning on ruby 2.5 (`BigDecimal.new is deprecated`) and one regular warning (`warning: ambiguous first argument; put parentheses or a space even after '-' operator`).
To enable warnings during tests : `bundle exec rspec --warnings`
> Remove deprecation warnings

- lib/money/money/arithmetic.rb
- spec/money/arithmetic_spec.rb
This works as expected:
```ruby
Money.new(0) - Money.new(100)
=> #<Money fractional:-100 currency:USD>
```
But this does not:
```ruby
0 - Money.new(100)
=> #<Money fractional:100 currency:USD>
```
A common case for the above would be when summing a list and subtracing a value from the sum. For instance, this works:
```ruby
my_list = [Money.new(-10), Money.new(10)]
my_list.sum - Money.new(100)
=> #<Money fractional:-100 currency:USD>
```
But if you happen to end up with an empty list and forget to handle it:
```ruby
my_list = []
my_list.sum - Money.new(100)
=> #<Money fractional:100 currency:USD>
```
Uh oh! That's a bug!
Rather than requiring the developer to know to provide a default `Money.empty` value to `.sum` (which would fix the latter issue, but not the former one), this PR …
> Fix case of coerced zero numeric subtraction.

- lib/money/money.rb
- lib/money/money/formatter.rb
- lib/money/money/formatting_rules.rb
Formatting is a separate concern and there's no good reason for including it into the `Money` class. This PR extracts it into a class which `Money` uses to format the output.
> Extract formatting into a separate module

- lib/money/currency.rb
Because it is exactly the same thing and there's no need for `calculate_decimal_places` and caching nonsense
> Alias Currency#exponent with decimal_places

- lib/money/money/formatter.rb
- spec/money/formatting_spec.rb
Current regexp for south asian number formatting does not support whole numbers. This PR replaces it with the one that supports it, however there's an issue with INDIAN_BAR currency because it uses 4 decimal points causing regexp to match it as the whole part.
A potential solution would be a slight redesign of formatting logic — treat the whole part separate from the decimal part combining them after.
If anyone can come up with a better regexp I'd really appreciate it.
> Fix for south asian number formatting

- lib/money/money/formatter.rb
- spec/money/formatting_spec.rb
The former solution is really messy and ineffective — reformatting the value back and forth to get the correct result. This new solution establishes the correct numeric value first, splits it into whole and decimal parts, which are then formatted individually before being combined into the result.
While testing this I realised than MGA formatting was incorrect the whole time (this might need clarification from someone who's familiar with the currency better). I think it should be something like this:
1 Iraimbilanja = 0.2 arairy
1.5 Iraimbilanja = 0.3 ariary
6 Iraimbilanja = 1.2 ariary
You get the same result when using `.to_f` instead of a `.format`.
> Refactor formatter

- lib/money/money.rb
- spec/money_spec.rb
I want to be able to use `infinite_precision` for most of my Money values (derived from formulas), but sometimes set the precision along the way to be used in calculations down the line.
This PR adds an optional rounding precision along with the already optional rounding strategy.
> Custom round precision when using `infinite_precision`

- lib/money/currency.rb
- spec/currency_spec.rb
Hey, sometimes you need to create inherited currencies, where there are couple of changes. As for me, working with cryptocurrencies, I often need almost same currency with just different precision.
```ruby
Money::Currency.register(
priority: 1,
iso_code: 'BTC',
iso_numeric: 4217,
name: 'Bitcoin',
symbol: 'BTC',
symbol_first: false,
subunit: 'Satoshi',
subunit_to_unit: 1_0000,
thousands_separator: '.',
decimal_mark: ','
)
```
It is really useful to have inheritance interface
```ruby
Money::Currency.inherit(:btc, {
iso_code: 'BTC8',
subunit_to_unit: 1_0000_0000
})
```
Let me know what you think about that? 
P.S. Not making any changelog changes because I'm not bumping version. Please mention me, if you would like me to do that.
> Adding inheritance for currencies

- lib/money/money.rb
- spec/money_spec.rb
`Money#split(num)` handles even splits, but if we want a weighted distribution `Money#allocate(splits)` has the condition that the splits sum to a number less than 1 (including any fraction or negative number). This seems like an arbitrary restriction given that the code works fine for any splits at all.
> Do not restrict allocations sum

- money.gemspec
Only change is dropping Ruby 1.9.3 support: https://github.com/svenfuchs/i18n/pull/409
> Support i18n 1.0

- lib/money/money.rb
- lib/money/money/formatter.rb
- spec/money/formatting_spec.rb
There's a good part of duplicated logic between the `Formatter` and `#to_s`. This change re-implements `#to_s` to use the `Formatter` as keeping 2 different solutions in place might result in confusing differences.
There's a potential issue of a decimal part being shown when displaying a currency with `subunit_to_unit = 1` and `infinite_precision = true`.
> Use Formatter for #to_s

- CHANGELOG.md
- Gemfile
- README.md
- lib/money/bank/variable_exchange.rb
- lib/money/currency/loader.rb
- lib/money/money.rb
- lib/money/money/formatter.rb
- lib/money/money/formatting_rules.rb
- spec/bank/variable_exchange_spec.rb
- spec/currency_spec.rb
- spec/money/arithmetic_spec.rb
- spec/money/formatting_spec.rb
- spec/rates_store/memory_spec.rb
Switching to ruby new hash syntax as default across all the RubyMoney projects
> Switch to new ruby hash syntax

- README.md
These links have changed since the `Formatting` got renamed to `Formatter`
> Fix formatting links in the README

- lib/money/money/arithmetic.rb
- spec/money/arithmetic_spec.rb
When attempting to upgrade the 'money' gem in one of our projects to [version 6.11.0](https://github.com/RubyMoney/money/releases/tag/v6.11.0), I noticed that some tests started failing. I could pinpoint these failures to some functionality that summed non-USD (or non-default) currency `Money` objects.
You could reproduce it as follows:
```ruby
[Money.from_amount(10.00, 'EUR'), Money.from_amount(5.00, 'EUR')].sum
```
I have added a failing spec, and then fixed it by passing the 'currency' to the `Money.empty` initializer.
> Fix issue with summing non-default/USD currency 'Money' objects

- lib/money/money.rb
- lib/money/money/formatting_rules.rb
- spec/money_spec.rb
During `Money#to_s` refactoring (https://github.com/RubyMoney/money/commit/f260b9dc1dcdca28b67f6b3671c04241f0f89fce) a regression was introduced that would take default formatting rules into consideration. This PR fixes the regression.
> Ignore formatting defaults for Money#to_s

- lib/money/money.rb
- spec/money_spec.rb
There has been a couple of problems with using `currency.decimal_mark` when calling `to_s`. Primarily the inconsistency with how `money-rails` validates input, relying on i18n for determining acceptable decimal mark.
This PR restores the behaviour to be similar to the original. Following the path of least resistance here, since it turned out that this wasn't covered by enough unit-tests and the refactor did alter the behaviour in some cases.
> Respect i18n in #to_s

- README.md
- lib/money/money.rb
- spec/money_spec.rb
The `Money` was designed to be an immutable value object, however `currency_as_string=` breaks this promise and will be deprecated.
As a replacement a new method `#with_currency` is introduced which returns a new instance in a given currency.
> Deprecate currency_as_string

- lib/money/money/formatter.rb
- spec/money/formatting_spec.rb
In response of #775 
When using formatter's `html: true` option, all amount's string parts
will be wrapped in html elements (symbol, whole part, decimal mark,
decimal part and, if `with_currency` is true, currency).
Also deprecated html_wrap_symbol option, since it will be always wrapped
with `html: true` option.
@antstorm I'm not sure about deprecation part though, because we potentially introduce breaking change here. Are you going to make a major release or should we introduce temporary option which enables this new type of behaviour?
>  Wrap all amount parts when html option is used

- lib/money/money.rb
- spec/money_spec.rb
We used to return `self` when `infinite_precision` was set to `false`. This can cause issues as the result might change based on the global `rounding_mode` setting — the result of keeping the `fractional` part unchanged and only relying on the `rounding_mode` to adjust the return value.
Another manifestation of this problem might come in accumulating error during arithmetics operations:
```ruby
money_1 = Money.new(10.9).round(BigDecimal::ROUND_DOWN)
money_2 = Money.new(10.9).round(BigDecimal::ROUND_DOWN)
expect(money_1 + money_2).to eq(Money.new(20))
```
This would have returned `22` before the fix.
More examples and discussion in #638
> Respect rounding mode when infinite_precision is false

- lib/money/money/constructors.rb
- spec/money/constructors_spec.rb
Memoization of #empty can cause issues because the `default_bank` is used when initializing a Money object. In case it will get changed after `#empty` got memoized — the memoized result will no longer reflect the latest state:
```ruby
Money.zero.bank == Money.default_bank # => true
Money.default_bank = Money::Bank::VariableExchange.new
Money.zero.bank == Money.default_bank # => false
```
The performance implications of this in the real world might not be as dramatic and I would rather avoid dealing with cache invalidation if possible.
Fixes #779
> Remove memoization for #empty/#zero

- lib/money/money.rb
- lib/money/money/formatter.rb
- lib/money/money/formatting_rules.rb
- spec/money/formatting_spec.rb
This PR adds support for providing formatting template to the `.format` call. It works the same way as the `format` option in I18n.
`%u` will get replaced by the symbol (if present) and `%n` will get replaced by the number.
Related options (`:symbol_position`, `:symbol_before_without_space` and `:symbol_after_without_space`) work the before, however when `:format` is supplied these are ignored.
> Add :format option for Formatter

- money.gemspec
i18n version 1.1 was released a couple of days ago. The tests ran without failures with this new release, so adjusted the version requirement.
> Support i18n 1.1

- lib/money/locale_backend/base.rb
- lib/money/locale_backend/errors.rb
- lib/money/locale_backend/i18n.rb
- lib/money/locale_backend/legacy.rb
- lib/money/money.rb
- lib/money/money/formatter.rb
- lib/money/money/locale_backend.rb
- spec/locale_backend/i18n_spec.rb
- spec/locale_backend/legacy_spec.rb
- spec/money/formatting_spec.rb
- spec/money/locale_backend_spec.rb
- spec/money_spec.rb
As identified many times before per-currency localisation is very misleading because money in the same currency should be formatted differently in different countries (the opposite is also true — amounts in different currencies should be formatted similarly in the same country).
This PR introduces a `LocaleBackend` abstraction that will be used for looking up translations. In order to retain the current behaviour a `Legacy` backend is added, however it will get deprecated soon along with the `use_i18n` flag.
You can choose not to use a locale backend, which will then fall back to using default values (`thousands_separator: '', decimal_mark: '.'`). This will be the default option in the future, breaking up the `i18n` dependency.
Rules submitted to `.format` call will always take priority, …
> Add locale_backend abstraction for translation lookups

- lib/money/money/formatting_rules.rb
`symbol_position`, `symbol_before_without_space` and `symbol_after_without_space` can all be expressed using the `format` option. Deprecating
> Deprecate old formatting rules in favour of format:

- money.gemspec
I see no reason for locking at patch version and non-semver.
> Improve versions-lock of `i18n` and `rspec` dependencies

- README.md
- lib/money/locale_backend/r18n.rb
- lib/money/money/locale_backend.rb
- money.gemspec
- spec/locale_backend/r18n_spec.rb
- spec/money/formatting_spec.rb
- spec/spec_helper.rb
https://github.com/ai/r18n
Replace `Money.use_i18n` [Boolean] with `Money.i18n_backend` [Symbol]
Drop Ruby 1.9 support
> Add R18n locale backend

- lib/money/money/formatter.rb
- lib/money/money/formatting_rules.rb
* It seems to me that `to_s` could be divided into multiple methods based on operations it is performing.
* `number_formatting`, `sign`  & `currency_symbol`.
> refactoring to_s method

- lib/money/locale_backend/legacy.rb
- lib/money/money.rb
- spec/locale_backend/i18n_spec.rb
- spec/locale_backend/legacy_spec.rb
- spec/money/formatting_spec.rb
- spec/money_spec.rb
- spec/spec_helper.rb
This should now be fully replaced with `Money.locale_backend`
> Remove use_i18n option

- lib/money/money/formatting_rules.rb
- spec/money/formatting_spec.rb
This is a very old behaviour that isn't used anyways
> Deprecate old `format` rules

- config/currency_backwards_compatible.json
- config/currency_iso.json
- config/currency_non_iso.json
This pull request fixes https://github.com/RubyMoney/money/pull/801
Had to change the symbol of Venezuelan Bolívar to "Bs.F" instead of just "Bs", to correct "Format 'Bs1.999,98' for VEF is ambiguous with currency VES."
> Deprecate bolívar fuerte and add bolívar soberano

- README.md
- lib/money/locale_backend/currency.rb
- lib/money/locale_backend/legacy.rb
- lib/money/money.rb
- lib/money/money/locale_backend.rb
- spec/locale_backend/currency_spec.rb
This will allow to not rely on `use_i18n` at all, making the deprecation cleaner. It also makes the messaging clearer.
Fixes #816
> Add explicit "per currency" localisation

- lib/money/money.rb
- spec/money_spec.rb
TIL: both `BigDecimal('NaN')` and `BigDecimal('Infinity')`are valid.
However these should not be allowed, because they make no sense as Money amounts and will cause problems down the line
Fixes #831
> Disallow initializing Money with non-finite amounts

- lib/money/locale_backend/currency.rb
- lib/money/locale_backend/i18n.rb
- lib/money/locale_backend/r18n.rb
- lib/money/money/formatter.rb
- lib/money/money/formatting_rules.rb
- spec/locale_backend/currency_spec.rb
- spec/locale_backend/i18n_spec.rb
- spec/locale_backend/r18n_spec.rb
- spec/money/formatting_spec.rb
Add localisation support for `:format` option, allowing to use I18n to provide a template for formatting
> Localize :format

- README.md
This was a really surprising discovery for me. It's also not mentioned anywhere in the readme, so I added this documentation, based on comments from #707.
> Add documentation for rounding mode.

- .travis.yml
- Gemfile
- money.gemspec
Since Bundler 2.0 was released, the build has failed!
In Travis CI we install the [latest version of Bundler (2.0.1)](https://travis-ci.org/RubyMoney/money/jobs/475145276#L473), but our gemspec [specifies we must use `~> 1.3`](https://travis-ci.org/RubyMoney/money/jobs/475145276#L488) which excludes Bundler v2.
To fix this:
* remove the constraint on the Bundler version from the gemspec (this allows developers to use the Bundler version they desire).
* Install Bundler 1.17.3 on TravisCI (Bundler v2 requires Ruby >= 2.3. We can bump up to Bundler v2 after we remove the legacy Ruby versions from the build matrix.)
Additionally the latest release of i18n is incompatible with legacy Rubies. For these Rubies the i18n has been pinned to the last known working version: 1.2.0.
> Fix the build

- lib/money/locale_backend/i18n.rb
- spec/locale_backend/i18n_spec.rb
This will allow for smoother transition of money-rails to support LocaleBackend. This behaviour is not used directly by the Money gem and probably never will be because we have a much better symbol database compared to rails-i18n.
> Allow :symbol lookup in LocaleBackend::I18n

- lib/money/money/allocation.rb
- spec/money/allocation_spec.rb
This leads to an error when attempting to allocate a zero value, and the
zero value is the first argument in parts.
Example:
```
[1] pry(main)> Money.new(100, "USD").allocate([1, 1, 0])
=> [#<Money fractional:50 currency:USD>, #<Money fractional:50 currency:USD>, #<Money fractional:0 currency:USD>]
[2] pry(main)> Money.new(100, "USD").allocate([0, 1, 1])
ZeroDivisionError: divided by 0
[3] pry(main)> Money.new(100, "USD").allocate([1, 1, 0.0])
=> [#<Money fractional:50 currency:USD>, #<Money fractional:50 currency:USD>, #<Money fractional:0 currency:USD>]
[4] pry(main)> Money.new(100, "USD").allocate([0.0, 1, 1])
FloatDomainError: NaN
```
> Prevent Divide By Zero in Money#allocate

- money.gemspec
This will ensure that all the dotfiles, specs, Gemfiles and other non-required files are not included in the packaged gem
> Only included required files in packaged gem

- lib/money/money/arithmetic.rb
- spec/money/arithmetic_spec.rb
Previously these operations would fail with `NoMethodError: undefined method `zero?' for nil:NilClass` which is not very descriptive.
Also added a descriptive message for adding/subtracting non-zero Numeric values. Ideally these errors should have been `ArgumentError`s, but that is potentially a breaking change.
Fixes #851
> Raise explicit errors for +/- operations

- lib/money/money/formatting_rules.rb
- spec/money/formatting_rules_spec.rb
This behaviour is confusing and can be potentially harmful as the hash that was
passed in gets modified
> Do not modify passed-in options in FormattingRules

- lib/money/currency.rb
- lib/money/money.rb
- spec/money/arithmetic_spec.rb
- spec/money/formatting_spec.rb
- spec/money_spec.rb
- spec/spec_helper.rb
> Set Money.default_currency to nil.

- README.md
- lib/money/money.rb
- spec/money_spec.rb
The current default rounding mode is `ROUND_HALF_EVEN` also known as the "Banker's Rounding". This means that 1.4, 1.5, 1.6 are rounded to 2, however 2.4, 2.5, 2.6 are also rounded to 2 (towards nearest even number).
This helps minimizing the accumulated error when performing big amounts of operations, however this is not intuitive and can cause confusion, which is not expected from a default setting.
Changing this to `ROUND_HALF_UP`, which is a common sense approach. Will add this to post-install message as a warning.
> Switch default rounding mode to ROUND_HALF_UP

- AUTHORS
- CHANGELOG.md
- config/currency_iso.json
Updates various currency configuration for the Zambian Kwacha. Used the [Bank Of Zambia](http://www.boz.zm/currency-family.htm) as a resource to confirm the updates.
> Updates currency config for ZMW

- lib/money/money.rb
- spec/money_spec.rb
This is no longer supported, use `with_rounding_mode` instead
> Remove ability to call Money#rounding_mode with a block

- lib/money/money/formatting_rules.rb
I'll keep those methods for now as they might be useful for some devs, however these should not force everyone to depend on I18n.
> Make I18n dependency optional

- lib/money/money.rb
- spec/money_spec.rb
`Money.default_currency` will change to `nil` in v7. Raising a warning to inform everyone ahead of time and prevent potential issues
> Raise warning on using `Money.default_currency`

- lib/money/money.rb
- spec/money_spec.rb
The default `Money.rounding_mode` will change to `ROUND_HALF_UP` in v7. Warning everyone ahead of time to minimise potential impact
> Raise warning on using default Money.rounding_mode

- lib/money/rates_store/memory.rb
- spec/bank/variable_exchange_spec.rb
- spec/rates_store/memory_spec.rb
Remove without_mutex option as it's now irrelevant.
> Potential fix for #897. Use monitor for recursive mutual exclusion.

- README.md
- lib/money/bank/variable_exchange.rb
- spec/bank/variable_exchange_spec.rb
In Rails 6.0 zeitwerk is used as default class loader. It's not allowing using classes from `app` directory in initializers:
```
DEPRECATION WARNING: Initialization autoloaded the constants ExchangeRate
Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.
Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ExchangeRate, for example,
the expected changes won't be reflected in that stale Class object.
These autoloaded constants have been unloaded.
Please, check the "Autoloading and Reloading Constants" guide for solutions.
```
To workaround that I added the ability to pass custom store as a string and load the actual class (like …
> Allow passing custom store as a string to Money::Bank::VariableExchange

- lib/money/rates_store/memory.rb
Fix a regression introduced in #898 that caused subclasses of `Money::RatesStore::Memory` to stop working
> Fix RatesStore::Memory regression

- lib/money/money.rb
- spec/money_spec.rb
👋 Hi, so hear me out -- these warnings are useful, but not at the frequency that #882 and #883 ended up causing.
For an application that makes sufficient usage of `Money`, these changes essentially cause a flood of `[WARNING]` logs (like, potentially in the millions, because they log on _each getter call_) which could cause all sorts of problems -- filling disks, flooding sockets, taking entire systems down, and potentially costing a lot of real world $$$ to the myriad of gem consumers.
I did a little digging and I understand how, when `set_defaults` gets triggered, there is no way to know for sure whether the consumer will eventually configure these on their own. But my thought is that by the time the getters are being called, the consumers should've manually configured, and so …
> Only warn once if defaults are not explicitly set

- CHANGELOG.md
- lib/money/money.rb
- lib/money/money/allocation.rb
- spec/bank/variable_exchange_spec.rb
- spec/money/allocation_spec.rb
I've been going throug the docs and I noticed few issue with them (wrong YARD formatting, wording, typos). Here is a PR with some fixes, mostly for methods I did look up.
> Fixes to the Money class docs

- README.md
Based on the recently introduced warning about the default rounding method changing I endeavoured to provide this value in my initializer. Doing so proved a little confusing as there was no mention of what values were expected and I had to dig through the initial PR (https://github.com/RubyMoney/money/pull/883) to figure it out.
I've added a short snippet to the documentation about how to set the round_mode and what values are expected. This includes a link to the `BigDecimal` documentation that outlines the possible values.
> Rounding Documentation Update

- config/currency_iso.json
According to https://en.wikipedia.org/wiki/West_African_CFA_franc, symbol is `CFA` rather than `FR`
> Updates symbol for Central African Franc

- lib/money/bank/variable_exchange.rb
- spec/money_spec.rb
Right now double conversion raises if `Money.default_bank` doesn't have require rate.
It's even more complicated if original bank uses historical rates from OXR *of specific date*,
but second conversion uses default bank *of today*
> Allow double conversion using same bank

- Rakefile
- lib/money/money.rb
Using `attr_accessor` already defines `attr=`, so now that we have
custom writers, we don't need to define them with `attr_accessor`.
Warnings:
lib/money/money.rb:162: warning: method redefined; discarding old locale_backend=
lib/money/money.rb:172: warning: method redefined; discarding old use_i18n=
Additionally, add `-w` to rspec's Ruby opts, so that we see such errors
earlier.
> Prevent method redefinition warnings

- spec/spec_helper.rb
This PR is continued  #921. I suppress warnings when test is executing.
This implementation may be not good because warn method is defined three classes.
> Suppress warnings when test is executing

- lib/money/money/arithmetic.rb
- lib/money/rates_store/memory.rb
Some warnings are remain because it is defined by using `Module#define_method`.
```console
~/ghq/github.com/taki/money %be rake yard                                                                                                           master
[warn]: @param tag has unknown parameter name: other_money
in file `lib/money/money/arithmetic.rb' near line 55
[warn]: @param tag has unknown parameter name: other_money
in file `lib/money/money/arithmetic.rb' near line 125
[warn]: @param tag has unknown parameter name: other_money
in file `lib/money/money/arithmetic.rb' near line 125
[warn]: @param tag has unknown parameter name: other_money
in file `lib/money/money/arithmetic.rb' near line 125
[warn]: @param tag has unknown parameter name: other_money
in file `lib/money/money/arithmetic.rb' …
```
> Fix yard warnings

- lib/money/bank/variable_exchange.rb
- spec/bank/variable_exchange_spec.rb
Using `Marshal.load` with a crafted payload can lead to remote code execution
Fixes #928
> Print warning when using unsafe serializer for rate import

- lib/money/currency.rb
- spec/currency_spec.rb
Provide public API to initialize Money::Currency.
Money::Currency provides registered currency within the ruby process if the currency is once registered.
It became a problem for me on the test context.
Once the currency was overwritten by using `register`, there is no way to initialize the currency table within the ruby process.
I could solve that by using instance_variable_set, and class_variable_set like below.
```ruby
Money::Currency.class_variable_set('@@instances', {})
Money::Currency.instance_variable_set('@table', Money::Currency::Loader.load_currencies)
```
But I suppose it might be good to provide `initialize` API as a library.
> [Proposal]  Public API to initialize currency class variable @@instances and instance variable @table

- lib/money/money.rb
- spec/money_spec.rb
Similar to `Money.default_currency` this will allow resolving the default bank dynamically when called
> Allow specifying default_bank as a lambda

- README.md
Add the missing `each_rate` method, simplify existing methods. I also dropped the comment for `ApplicationRecord` in favor of using it directly. Rails < 5 is long gone.
> Improve documentation for the ActiveRecord store

- config/currency_iso.json
- spec/money/formatting_spec.rb
Issue #957 - According to the [ISO-4217](https://en.wikipedia.org/wiki/Currency_symbol) and [Bahraini dinar Wiki](https://en.wikipedia.org/wiki/Bahraini_dinar) and [Bahraini dinar Ar Wiki](https://ar.wikipedia.org/wiki/%D8%AF%D9%8A%D9%86%D8%A7%D8%B1_%D8%A8%D8%AD%D8%B1%D9%8A%D9%86%D9%8A) the correct currency symbol for this Bahraini Dinar should be د.ب instead of ب.د
> Fix Bahraini dinar symbol

- AUTHORS
- CHANGELOG.md
- lib/money/money/allocation.rb
- lib/money/version.rb
- spec/money_spec.rb
Money#allocate was failing to round-robin remaining pennies in the case of an array of all zeros. This change treats the case of an Array of size N of all zero values, the same as for passing in a Numeric of value N for even distribution.
> Fix allocate for array of all zeros

- README.md
- lib/money/money/formatter.rb
* Avoid warning messages when calling `#format_decimal_part`
like this:
```
[DEPRECATION] `Money.infinite_precision` is deprecated - use `Money.default_infinite_precision` instead
```
* Tweaks to README.
> [6.14.0] Avoid warning messages when calling `#format_decimal_part`: Money.infinite_precision -> Money.default_infinite_precision

- config/currency_iso.json
- spec/money/formatting_spec.rb
As described in #966, we noticed that the default format for the `CHF` currency changed with the last version released. This PR restores the previous format and, I think, needs to be part a patch release to ensure backward compatibility.
If accepted, I can send another PR to update the CHANGELOG including this in the next patch level (or making the change in this PR directly if #968 will be merged before).
> Revert CHF format changes introduced in v6.14

- CHANGELOG.md
This PR also removes 6.13.9 which doesn't seem to be ever been released.
> Add the CHANGELOG entries for 6.14.0

- AUTHORS
- CHANGELOG.md
- lib/money/money/formatter.rb
- lib/money/money/formatting_rules.rb
- lib/money/version.rb
- spec/money/formatting_spec.rb
To add an option to put the thousands separators according to a regex.
Use the ones previously defined in `Formatter#regexp_format` if not specified
Move the logic to fetch this regex to `FormatterRules`
Both the name and the path for the option are taken from [activesupport](https://api.rubyonrails.org/classes/ActiveSupport/NumberHelper.html#method-i-number_to_delimited)
> Allow specifying a delimiter pattern

- lib/money/money/formatting_rules.rb
- spec/money/formatting_spec.rb
As suggested in this comment https://github.com/RubyMoney/money/pull/981#discussion_r600023628, looking for `I18n.t('number.currency.format.delimiter_pattern', default: nil)` is quite expensive.
This PR drops support for that and enforces to pass this option when calling the `#format` method
> Drop `number.currency.format.delimiter_pattern` option parsing

- lib/money/money/formatter.rb
- spec/money/formatting_spec.rb
When configuration is set to use `thousands_separator: false`, using the locale or default separator cannot be done ambiguously.
Allow `thousands_separator: true` to be used to use the locale or default separator.
This will break for anyone using `true` as an actual separator.
```spec
Failures:
1) Money formatting #format :thousands_separator option (thousands_separator: true) works as documented
Failure/Error: expect(Money.us_dollar(100000).format(thousands_separator: true)).to eq "$1,000.00"
expected: "$1,000.00"
got: "$1true000.00"
(compared using ==)
2) Money formatting #format :thousands_separator option (delimiter: true) works as documented
Failure/Error: expect(Money.us_dollar(100000).format(delimiter: true)).to eq "$1,000.00"
expected: "$1,000.00"
got: "$1true000.00"
(compared …
```
> Allow true for thousands_separator

- README.md
The old badge is now outdated.
> fix: Use GitHub Actions badge in README

- .github/workflows/ruby.yml
This PR clarifies the CI configuration by removing generated comments.
> CI: Drop boilerplate comments

- money.gemspec
This gem exposes no executables, and test_files is not used by RubyGems.org.
> gemspec: Drop unused directives

- config/currency_non_iso.json
- spec/money/formatting_spec.rb
This adds [USDC ](https://www.circle.com/en/usdc) which a cryptocurrency stablecoin pinned to the US dollar.
Not sure if this is the place for introducing cryptocurrencies but opened this anyway since I have a use case in my app and would help others as well.
> Add USDC stablecoin

- .github/workflows/ruby.yml
- AUTHORS
- CHANGELOG.md
- spec/money_spec.rb
This PR adds Ruby 3.1 to the CI matrix.
To get this working I had to make some changes in a serialization test to support the Psych 4 safe load.  The odd part is that I couldn't find any matching code for loading `Money` objects in the actual gem.  I may have missed something.
> Add Ruby 3.1 to CI

- AUTHORS
- CHANGELOG.md
- config/currency_iso.json
Hello! 
One of our customers made us notice that the Georgian Lari symbol was changed back in 2014 and we should update it here too! 
More about it in the Wikipedia page: https://en.wikipedia.org/wiki/Georgian_lari
> update Georgian Lari symbol

- README.md
Without this method, calling save! throws an error that causes test suites to bomb.
Example stacktrace:
```
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/activerecord-6.1.5.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `marshal_dump' for MyExchangeRateARClass:Class (NoMethodError)
from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted.rb:306:in `method_missing'
from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted/adapters/active_record.rb:131:in `method_missing_with_attr_encrypted'
from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/money-6.13.8/lib/money/bank/variable_exchange.rb:69:in `marshal_dump'
from …
```
> Fix ActiveRecord custom exchange rate docs

- config/currency_iso.json
This is the "New Leone" introduced to Sierra Leone in July 2022.  The
previous currency (SLL) will remain valid until October 2022.
See:
* https://www.reuters.com/article/leone-currency-idAFL8N2YI2E9
* https://en.wikipedia.org/w/index.php?title=ISO_4217&diff=1095269772&oldid=1095247155
> Add new SLE currency

- CHANGELOG.md
- config/currency_backwards_compatible.json
- config/currency_iso.json
On 2023-01-01, Croatia adopted the Euro and the HRK became obsolete.
https://economy-finance.ec.europa.eu/euro/eu-countries-and-euro/croatia-and-euro_en
This PR moves the definition of `HRK` to the backwards compatibility source file, consistent with other obsolete currencies.
> change(data): remove HRK (Croatian Kuna)

- CHANGELOG.md
- config/currency_iso.json
- lib/money/version.rb
I looked the format used across [Mercado Libre](https://www.mercadolibre.com/) LATAM properties like https://www.mercadolibre.com.pe/
I also asked about it to a Peruvian colleague. He informed me that they use `,` for decimal mark and `.` for thousands separator.
Because of that I'm changing it here.
> Change Peruvian Sol (PEN) decimal mark and thousands separator

- README.md
`.format` requires i18n locales explicit declaration
```ruby
[6] pry(main)> Money.from_cents(123).format
[DEPRECATION] You are using the default localization behaviour that will change in the next major release. Find out more - https://github.com/RubyMoney/money#deprecation
I18n::InvalidLocale: :en is not a valid locale
from /Users/friendlyantz/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/i18n-1.12.0/lib/i18n.rb:351:in `enforce_available_locales!'
[7] pry(main)> I18n.config.available_locales = :en
=> :en
[8] pry(main)> Money.from_cents(123).format
[DEPRECATION] You are using the default localization behaviour that will change in the next major release. Find out more - https://github.com/RubyMoney/money#deprecation
=> "$1.23"
[9] pry(main)> Money.locale_backend = :i18n
=> :i18n
[10] …
```
> explicit declaration of i18n locales

- config/currency_iso.json
- spec/money/formatting_spec.rb
As far as I can find anywhere, the correct formatting for CHF includes a space.
Similar PR on another project: https://github.com/invoiceninja/invoiceninja/issues/4109
> Add space to CHF format

- lib/money/money/formatting_rules.rb
- spec/money/formatting_rules_spec.rb
The current deprecation message for the before or after symbol suggests using a format string that includes spaces.  This is a small change so that the deprecation warning is more useful.
```
[12] pry(main)> money.format(symbol_position: :before, symbol: true)
[ruby-deprecation] [DEPRECATION] `symbol_position: :before` is deprecated - you can replace it with `format: %u %n`
=> "$23.45"
[13] pry(main)> money.format(format: "%u %n", symbol: true)
=> "$ 23.45"
[14] pry(main)> money.format(format: "%u%n", symbol: true)
=> "$23.45"
```
Co-authored-by: Alec Clarke <alec.clarke.dev@gmail.com>
> Update deprecation message to suggest correct formatting.

- spec/bank/base_spec.rb
- spec/bank/single_currency_spec.rb
- spec/bank/variable_exchange_spec.rb
- spec/currency_spec.rb
- spec/money/arithmetic_spec.rb
- spec/money_spec.rb
Also, `raise_error` better clarifies what is expected from specs and is also
shorter
- `ArgumentError` and `TypeError` are errors
- `DifferentCurrencyError`, `UndefinedSmallestDenomination`, and
`UnknownRate` inherit from `Error`
- `UnknownCurrency` inherits from `ArgumentError`
Close #1076
---
Requires #1078 to pass CI
> Fix deprecation warning when running specs

- money.gemspec
Make the gem more secure by requiring that all privileged operations by any of the owners require OTP.
Ref: https://guides.rubygems.org/mfa-requirement-opt-in/
> Opt-in for MFA requirement

- AUTHORS
- CHANGELOG.md
- money.gemspec
- spec/money/formatting_spec.rb
When using this gem in a project a warning is thrown.
```sh
/usr/local/bundle/gems/money-6.16.0/lib/money.rb:1: 
warning: 
bigdecimal was loaded from the standard library,  
but will no longer be part of the default gems since  
Ruby 3.4.0. Add bigdecimal to your Gemfile or gemspec.  
Also contact author of money-6.16.0 to add bigdecimal  
into its gemspec.
```
Shopify has a related issue to the topic, see their issue [#1772](https://github.com/Shopify/liquid/issues/1772).
> Fixes ruby deprecation warning regarding `bigdecimal` will be moved out from stdlib soon

- lib/money/money/formatting_rules.rb
- spec/money/formatting_spec.rb
I am using the money gem in a Japanese locale, but there seems to be an issue with the Money#format method, as indicated in the following link:
https://github.com/RubyMoney/money/blob/main/lib/money/money.rb#L627
I would like to make various changes as follows:
```
irb(main):001:0> Money.new(1000, "JPY").format(format: "%u %n foo bar")
=> "¥ 1,000 foo bar"
```
However, in reality, the format does not change:
```
irb(main):001:0> Money.new(1000, "JPY").format(format: "%u %n foo bar")
=> "1,000円"
```
Removing localize_formatting_rules Formatting would be the correct fix, but it has been rejected. I am waiting for the 7.0 release, but I cannot wait until then.
https://github.com/RubyMoney/money/pull/650
https://github.com/RubyMoney/money/pull/101
Without removing …
> Fix the issue where japanese formatting is no longer possible.

- .github/workflows/ruby.yml
- money.gemspec
Set minimum Ruby version to 3.1
Drop all EOL Ruby versions
Close #1086
---
Remove conditional on bigdecimal
- bigdecimal installs and works fine on all supported ruby versions
- The condition was checking for ruby version to be greater than 6.19,
which will not happen soon
- The condition is also evaluated on `rubygems`, and it is not correct
Close #1085
> Require Ruby 3.1 and fix bigdecimal requirement

- CHANGELOG.md
- config/currency_non_iso.json
- spec/money/formatting_spec.rb
> [!WARNING]  
> This fix can introduce a breaking change
Before:
```
Money.new(100, "USDC").to_s
=> "1.00"
```
After:
```
Money.new(100, "USDC").to_s
=> "0.000100" 
```
Close #1081
> Change USDC decimal places from 2 to 6

- CHANGELOG.md
- config/currency_iso.json
Hello! 
One of our customers reported a typo in the word "Sheqel" which should be "Shekel". A quick [Google search](https://www.google.com/search?q=ILS+currency&sca_esv=f39be0dcf9683254&sca_upv=1&ei=sWrEZtSlIPKH9u8P-6768Ag&ved=0ahUKEwiUwo2oqYOIAxXyg_0HHXuXHo4Q4dUDCA8&uact=5&oq=ILS+currency&gs_lp=Egxnd3Mtd2l6LXNlcnAiDElMUyBjdXJyZW5jeTIKEAAYgAQYQxiKBTIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABEiWClDnAVjRCHABeAGQAQCYAY8BoAHHB6oBAzUuNLgBA8gBAPgBAZgCCqAC4gfCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBcICBRAuGIAEmAMAiAYBkAYKkgcDNS41oAf5Lg&sclient=gws-wiz-serp) agrees with it.
Thanks!
> fix typo in Shekel

- CHANGELOG.md
- config/currency_iso.json
- spec/money/formatting_spec.rb
- spec/money_spec.rb
According to Stripe's documentation (https://docs.stripe.com/currencies#zero-decimal), MGA is included in their list of zero-decimal currencies, and this change ensures the Money gem correctly formats MGA amounts without decimal places.
Also from the [Wikipedia](https://en.wikipedia.org/wiki/Malagasy_ariary) entry:
> It is notionally subdivided into 5 iraimbilanja and is one of only two non-decimal currencies currently circulating (the other is the Mauritanian ouguiya). The names ariary and iraimbilanja derive from the pre-colonial currency, with ariary (from the Spanish word "real") being the name for a silver dollar. Iraimbilanja means "one iron weight" and was the name of an old coin worth 1⁄5 of an ariary. However, as of May 2023, the unit is effectively obsolete since the …
> Fix MGA (Malagasy Ariary) to be a zero-decimal currency

- CHANGELOG.md
- README.md
- lib/money/money.rb
- spec/currency_spec.rb
- spec/money/arithmetic_spec.rb
```
codespell **/*.rb *.md -L fils,arry,isnt,zar,befor -w
```
> Fix some typos

- lib/money/currency.rb
- lib/money/currency/heuristics.rb
- lib/money/money.rb
- lib/money/money/allocation.rb
- lib/money/money/formatter.rb
- lib/money/money/formatting_rules.rb
- lib/money/money/locale_backend.rb
- money.gemspec
- spec/currency/heuristics_spec.rb
- spec/currency/loader_spec.rb
- spec/currency_spec.rb
- spec/locale_backend/currency_spec.rb
- spec/locale_backend/i18n_spec.rb
- spec/locale_backend/legacy_spec.rb
- spec/money/allocation_spec.rb
- spec/money/arithmetic_spec.rb
- spec/money/constructors_spec.rb
- spec/money/formatting_rules_spec.rb
- spec/money/formatting_spec.rb
- spec/money/locale_backend_spec.rb
- spec/money_spec.rb
This magic comment is not needed anymore because the default encoding of source code files assumed by Ruby 2 is utf-8, and the minimum required Ruby version is 3.1
Autofixed with:
```
rubocop -a --only Style/Encoding
```
> Remove redundant encoding

- CHANGELOG.md
- money.gemspec
Require 1.9, the first version tested against Ruby 3.1
Close #1097
Ref: https://github.com/ruby-i18n/i18n/releases?page=2
> Bump Ruby I18n requirement

- lib/money/money/formatter.rb
The example for the documentation of the `:html_wrap_symbol` option showed the Ruby code from the previous option, `:disambiguate`, with the correct resulting string. Fixed to show the correct option being used in the example.
> FIx doc comment error in formatter.rb

- CHANGELOG.md
- lib/money/currency.rb
- lib/money/money.rb
- spec/currency_spec.rb
- spec/money_spec.rb
This is a part of fixing the https://github.com/RubyMoney/money-rails/issues/697
> Allow nil to be used as a default_currency

- .github/workflows/ruby.yml
---
Test against the latest stable version of JRuby
> Test against JRuby 10.0

- CHANGELOG.md
- lib/money/money/formatting_rules.rb
- spec/money/formatting_spec.rb
I am the one who submitted https://github.com/RubyMoney/money/pull/1067.
Since money 7.0.0 is being developed, I have made modifications to remove special handling for the Japanese language only.
By removing `Money::FormattingRules#localize_formatting_rules`, this will be a breaking change but will ensure consistent behavior across all languages.
This is the correct behavior as pointed out here:
https://github.com/RubyMoney/money/pull/650
> Remove special handling for Japanese language only

- CHANGELOG.md
- lib/money/money.rb
- sig/lib/money/money.rbs
Hello @RubyMoney/core and everyone else 👋🏻
Every major release deserves some sweet breaking changes (and we already have a few lined up 😬 ). We're prepping for version 7, and I’ll start by removing some methods that were deprecated a loooong time ago.
This PR removes `Money.infinite_precision=`, which was deprecated back in 2020 [see here](https://github.com/RubyMoney/money/commit/cf4e178ae59eab5d4eec83e36dfcf2aadaf3fd51)
> remove deprecated Money.infinite_precision method

- CHANGELOG.md
- README.md
- lib/money/money.rb
- sig/lib/money/money.rbs
- spec/money/arithmetic_spec.rb
- spec/money_spec.rb
- spec/spec_helper.rb
- spec/support/shared_examples/money_examples.rb
Hello @RubyMoney/core and everyone watching this 👀
Time for another round of deprecation cleanup 🧹🧹🧹
Now that [this PR](https://github.com/RubyMoney/money/pull/1095) has been merged, we can stop setting USD as the default currency, which was already anticipated back in [2019](https://github.com/RubyMoney/money/pull/882). 
It's about time we finally pull the trigger 💪🏻
> stop setting USD as default currency

- CHANGELOG.md
- README.md
- lib/money/money.rb
- sig/lib/money/money.rbs
- spec/money_spec.rb
Hello @RubyMoney/core and contributors!
Another deprecation out of the way before releasing a new major version! 🎉  This one was originally introduced in [this PR](https://github.com/RubyMoney/money/pull/883).
As explained in [this comment](https://github.com/RubyMoney/money/pull/883#issuecomment-562847214), the rationale for changing the default rounding mode is:
> the default rounding mode is ROUND_HALF_EVEN and they way it works might not be expected by people using this gem. It works best when aggregating with bigger amount of data and has an effect of minimizing rounding error, however when dealing with one off cases (for example rounding the result of a currency exchange) it's probably not as useful.
Out of curiosity – and to make sure we’re making the right call! – I asked ChatGPT …
> remove deprecations related with rounding mode

- lib/money/money/allocation.rb
```bash
ruby 3.3.3 (2024-06-12 revision f1c7b6f435) [arm64-darwin23]
Warming up --------------------------------------
generate_old   144.000 i/100ms
generate_new   570.000 i/100ms
Calculating -------------------------------------
generate_old      1.441k (± 0.7%) i/s  (693.93 μs/i) -      4.464k in   3.097879s
generate_new      5.576k (± 1.4%) i/s  (179.34 μs/i) -     17.100k in   3.067351s
Comparison:
generate_new:     5576.0 i/s
generate_old:     1441.1 i/s - 3.87x  slower
```
> Fix O(n2) to be O(n) for generate method

- AUTHORS
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- lib/money/money.rb
- sig/lib/money/money.rbs
- spec/money_spec.rb
This new method allows you to get a new Money instance rounded to the smallest denomination.
Closes #1130 
Allows us to simplify:
```rb
Money.new(Money.new(1_11, "CHF").round_to_nearest_cash_value, "CHF")
```
to:
```rb
Money.new(1_11, "CHF").to_nearest_cash_value
```
Ideally the `#round_to_nearest_cash_value` should have always returned an instance to act like the `#round` method. Introducing a new method avoids breaking previous code.
> Add `Money#to_nearest_cash_value` to return a rounded Money instance to the smallest denomination

- CHANGELOG.md
- lib/money/money.rb
- sig/lib/money/money.rbs
- spec/money_spec.rb
Hello @RubyMoney/core and contributors!
Another day, another deprecation remove that gets us closer to the release of 7.0.0!
This deprecation was introduced [here](https://github.com/RubyMoney/money/pull/776) in 2018!!!!! ABOUT TIME WE 🧹 .
> remove Money#currency_as_string and Money#currency_as_string= deprecated methods

- CHANGELOG.md
- lib/money/money.rb
- sig/lib/money/money.rbs
- spec/money_spec.rb
The `#dollars` method assumes the amount is in `USD` but does nothing to verify that.
```rb
Money.new(1_23, "USD").dollars # => 1.23 ✅
Money.new(1_23, "EUR").dollars # => 1.23 🤔
```
~I would like to add a warning to let people know that something is wrong here and so that in the future we can actually raise an error here.~
*Edit: Calling `#dollars` and `.from_dollars` are both now deprecated in favor of `#amount` and `.from_amount`.*
> Deprecate `Money#dollars` and `Money.from_dollars`
