RubyMoney/money

lib/money/currency.rb

refactoring Currency.initialize

---

config/currency_iso.json

I fixed mistake and added one new alternate symbol

Fix byr alternate sym

---

CHANGELOG.md
lib/money/version.rb

New version with correct BYR format

Up version to 6 5 1

---

CHANGELOG.md
lib/money/currency.rb
spec/currency_spec.rb
spec/spec_helper.rb

Add Currency::MissingAttributeError

---

index.html

Info on website is outdated(see README on source and website information)

update iso_code exception notice

---

AUTHORS
CHANGELOG.md
lib/money/money/formatting.rb
spec/money/formatting_spec.rb

This will allow currency symbols to be configured on a per-locale basis.

Adding support for translating currency symbols

---

AUTHORS
CHANGELOG.md
config/currency_iso.json
spec/money_spec.rb

Fix the subunit_to_unit values of the CLP

---

lib/money/money.rb
spec/money_spec.rb

Also `.from_amount` now respects `rounding_mode`.

Less objects allocations in .from_amount

---

CHANGELOG.md
config/currency_iso.json
spec/money_spec.rb

Revert "CLP subunit_to_unit change from 1 to 100"

---

README.md

include gem money-json-rates link to readme

add money-json-rates gem link to README.md

---

.gitignore
spec/currency/heuristics_spec.rb

Add spec for transliterate currency search pull request.

---

config/currency_iso.json

https://en.wikipedia.org/wiki/Bulgarian_lev

Update the currency symbol for Bulgarian lev

---

lib/money/money/formatting.rb
spec/money/formatting_spec.rb

:drop_trailing_zeros option

---

lib/money/money/arithmetic.rb

eql? should not accept Fixnum, TypeError is now raised in Ruby 2.3

Check for zero value without using eql? with a Fixnum

---

lib/money/money/formatting.rb

Revert "Ensure formatting methods are defined as public with class_eval"

---

AUTHORS
CHANGELOG.md

Forgot to feed the changelog in my recent pull requests.

Update changelog & authors for #577 #579 #584

---

config/currency_iso.json

from 1 July 2016 Belarus will get new money
http://www.exchangerate.com/currency-iso/belarussian-ruble-BYB.html
http://www.currency-iso.org/en/shared/amendments/iso-4217-amendment.html
I just updated iso currencies in config file

add new belarus currency

---

lib/money/currency.rb

…because the current one doesn't make sense

Fix Currency#exponent description

---

README.md

Hi,
just a small correction.
Please review & merge.
Cheers,
r11runner

corrected a typo in README

---

lib/money/money.rb
lib/money/money/arithmetic.rb
spec/money/arithmetic_spec.rb

See https://github.com/RubyMoney/money/issues/606#issuecomment-199233703

Money#== raises error for non-zero numeric values

---

config/currency_iso.json

just fixed syntax for currency UZS

UZS syntax fixed

---

lib/money/money/arithmetic.rb
spec/money/arithmetic_spec.rb

When conversions disallowed, raise errors on every x-currecy arithmetic operation

---

lib/money/money.rb
spec/money_spec.rb

Correct allocation for negative amounts

---

lib/money/bank/variable_exchange.rb
spec/bank/variable_exchange_spec.rb

Fix exchange issues when dealing with larger numbers

---

Gemfile

Addition to the steadily growing list of gems dropping ruby 1.9.3 support…

Lock term-ansicolor version for ruby 1.9.x

---

config/currency_iso.json

Change symbol_first to false for RON

---

.travis.yml

RVM fail to install on travis
https://github.com/rvm/rvm/issues/3617
Cheers

Allow failures from rubinius

---

README.md
lib/money/currency.rb
money.gemspec

I didn't update AUTHORS because this is no big deal.

Update links to HTTPS

---

config/currency_iso.json

I'm from Sri Lanka & the previous html_entity symbol was wrong for LKR.

#693 LKR currency html_entity symbol error fix

---

config/currency_iso.json

It should be $ like USD. Fixes #720

Fix html_entity for ARS

---

money.gemspec

Fixes a vulnerability in older yard versions

Update yard dependency to 0.9.11

---

lib/money/money/arithmetic.rb
spec/money/arithmetic_spec.rb
spec/spec_helper.rb
spec/support/shared_examples/money_examples.rb

https://github.com/RubyMoney/money/issues/740

Pass bank to initializer in arithmetic methods

---

lib/money/money.rb

Replace the implementation with simpler and more performant one

Use String#rjust for subunit padding

---

README.md

Improve text of the I18n troubleshooting in the README

---

money.gemspec

Add metadata to display as direct links on the rubygems page for this library

Add gem metadata

---

.travis.yml

And update `9.1` branch to `9.1.17`

Add jruby-9.2 to .travis.yml

---

config/currency_backwards_compatible.json
config/currency_iso.json

Fixes https://github.com/RubyMoney/money/issues/797
rspec tests pass.

Lithuania and Latvia use Euro after 2015

---

lib/money/currency.rb
spec/currency_spec.rb

Check if a Currency is iso or not

---

lib/money/money.rb
lib/money/money/formatter.rb
lib/money/money/formatting_rules.rb
spec/money/formatting_spec.rb
spec/money_spec.rb

These methods and options are now fully deprecated and should have non-deprecated alternatives

Drop deprecated methods and formatting options

---

lib/money/currency.rb
spec/currency_spec.rb

Fix incorrect behaviour of #find_by_currency_iso when given empty input

---

lib/money/money.rb
spec/money_spec.rb

Replacing `Money.roudning_mode` with a block

Add Money.with_rounding_mode

---

.travis.yml

Seems to have issues with jruby on the latest dist

Change dist to trusty to support older rubies

---

config/currency_iso.json

This seems to be the only one missing a symbol.

Add symbol for uzs

---

lib/money/money.rb
spec/money_spec.rb

Currency:  from USD to nil
Rounding:  from ROUND_HALF_EVEN to ROUND_HALF_UP
The warnings were added in #882 and #883 and refined in #902.

Warn about changing defaults with both the old (current) and new values.

---

README.md

Document how to localize currency position format

---

lib/money/money.rb
lib/money/money/arithmetic.rb

Extracted from https://github.com/RubyMoney/money/pull/886

Define Money#dup_with method

---

lib/money/money.rb
spec/money/arithmetic_spec.rb
spec/money/formatting_spec.rb
spec/money_spec.rb
spec/spec_helper.rb

Continuation of https://github.com/RubyMoney/money/pull/912

Default infinite precision

---

lib/money/bank/variable_exchange.rb
lib/money/money.rb

Continuation of https://github.com/RubyMoney/money/pull/913

New initializer keyword arguments

---

lib/money/money/arithmetic.rb
spec/money/arithmetic_spec.rb

Always allow comparison with zero Money

---

.gitignore
lib/money/money.rb
spec/money/arithmetic_spec.rb
spec/money/constructors_spec.rb
spec/money_spec.rb

* Raise DefaultCurrencyNotSetOrPassed exception.
* After checking default currency this exception is raised.

Raise exception when default currency is not set or passed as parameter

---

AUTHORS
CHANGELOG.md
README.md
lib/money/money.rb
lib/money/version.rb
spec/money_spec.rb

As discussed in https://github.com/RubyMoney/money/issues/972

Adding Money.from_cents constructor for explicitness.

---

CHANGELOG.md
config/currency_iso.json

This should close #1014. Any feedback is welcome!

Add Second Dobra (STN) from Sao Tome and Principe

---

README.md

Add example `Redis` store implementation to save exchange rates to a redis database

Redis store example implementation

---

.github/workflows/ruby.yml
CHANGELOG.md

- Update deprecated CI action
- Test against Ruby 3.2

Improve CI

---

CHANGELOG.md

Ref: #1023
Close #1066
[ci skip]

Add SLE to 6.18.0 changelog

---

README.md

Pretty sure I successfully removed this repo from Code Climate, but opening this PR (with the badge removal) to verify 🤞

Remove Code Climate
